PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT  ?name
WHERE
{
    GRAPH ?g {
        ?s ?p ?o
    }
    BIND(REPLACE(str(?g), "^urn:gleaner\\.io:eco:([^:]+):.*", "$1") AS ?name)
    FILTER regex(str(?g), "^urn:gleaner.io:eco")
}
ORDER BY ?name

