PREFIX schema: <https://schema.org/>

SELECT DISTINCT   ?vm ?name ?minValue ?maxValue ?propertyId ?unitCode ?unitText
WHERE {
  VALUES ?propertyId {
    "https://vocab.nerc.ac.uk/collection/P01/current/DBINAA01/"
    "https://vocab.nerc.ac.uk/collection/P01/current/ADEPZZ01/"
    "https://vocab.nerc.ac.uk/collection/P01/current/DEPHPRST/"
  }

  GRAPH ?g {
    ?subj schema:variableMeasured ?vm .
    ?vm a schema:PropertyValue ;
        schema:name ?name ;
        schema:minValue ?minValue ;
        schema:maxValue ?maxValue ;
        schema:propertyID ?propertyId .

    OPTIONAL { ?vm schema:unitCode ?unitCode . }
    OPTIONAL { ?vm schema:unitText ?unitText . }
  }
  FILTER(CONTAINS(STR(?g), "bodc"))
}
ORDER BY ?name ?subj
LIMIT 400