# Count subjects with GeoSPARQL geometry or schema:spatialCoverage.
PREFIX schema: <https://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT (COUNT(DISTINCT ?s) AS ?sCount)
WHERE {
  {
    {
      ?s geo:hasGeometry ?o .
    }
    UNION
    {
      ?s schema:spatialCoverage ?o .
    }
  }
  UNION
  {
    GRAPH ?g {
      {
        ?s geo:hasGeometry ?o .
      }
      UNION
      {
        ?s schema:spatialCoverage ?o .
      }
    }
  }
}
